import {
  ApartmentOutlined,
  AreaChartOutlined,
  DashboardOutlined,
  ProfileOutlined,
  UserOutlined,
} from "@ant-design/icons";

export const commonRoutes = [
  {
    id: "data",
    label: "Data Management",
    route: "/data",
    icon: <ProfileOutlined />,
  },
  {
    id: "insights",
    label: "Insights Management",
    route: "/insights",
    icon: <AreaChartOutlined />,
  },
];

export const userTypes = [
  {
    id: "user_1",
    userName: "superadmin",
    password: "superadmin@123",
    role: "super_admin",
    name: "Sudhir As Super Admin",
    email: "sudhir@gmail.com",
    isApproved: true,
    createdBy: "super_admin",
    featureConfig: {
      viewUser: true,
      createUser: true,
      editUser: true,
      deleteUser: true,
      createWorkFlow: true,
      editWorkFlow: true,
      deleteWorkFlow: true,
      viewWorkFlow: true,
      createDataItem: true,
      editDataItem: true,
      deleteDataItem: true,
      viewDataItem: true,
    },
    permittedRoutes: [
      {
        id: "dashboard",
        label: "Dashboard",
        route: "/dashboard",
        icon: <DashboardOutlined />,
      },
      {
        id: "user",
        label: "User Management",
        route: "/user",
        icon: <UserOutlined />,
      },
      ...commonRoutes,
      {
        id: "workflow",
        label: "Workflow Management",
        route: "/workflow",
        icon: <ApartmentOutlined />,
      },
    ],
  },
  {
    id: "user_2",
    userName: "admin",
    password: "admin@123",
    role: "admin",
    name: "Sudhir As Admin",
    email: "sudhir@gmail.com",
    createdBy: "super_admin",
    isApproved: true,
    featureConfig: {
      viewUser: true,
      createUser: true,
      editUser: true,
      deleteUser: true,
      createWorkFlow: false,
      editWorkFlow: true,
      deleteWorkFlow: true,
      viewWorkFlow: true,
      createDataItem: false,
      editDataItem: true,
      deleteDataItem: false,
      viewDataItem: true,
    },
    permittedRoutes: [
      {
        id: "dashboard",
        label: "Dashboard",
        route: "/dashboard",
        icon: <DashboardOutlined />,
      },
      {
        id: "user",
        label: "User Management",
        route: "/user",
        icon: <UserOutlined />,
      },
      ...commonRoutes,
    ],
  },
  {
    id: "user_3",
    userName: "user",
    password: "user@123",
    name: "Sudhir As User",
    email: "sudhir@gmail.com",
    createdBy: "user_2",
    role: "user",
    isApproved: true,
    featureConfig: {
      viewUser: false,
      createUser: false,
      editUser: false,
      deleteUser: false,
      createWorkFlow: false,
      editWorkFlow: false,
      deleteWorkFlow: false,
      viewWorkFlow: true,
      createDataItem: true,
      editDataItem: false,
      deleteDataItem: false,
      viewDataItem: true,
    },
    permittedRoutes: [
      {
        id: "dashboard",
        label: "Dashboard",
        route: "/dashboard",
        icon: <DashboardOutlined />,
      },
      ...commonRoutes,
    ],
  },
  {
    id: "user_4",
    userName: "user@gmail.com",
    password: "user@123",
    name: "Sudhir (user@gmail.com)",
    email: "sudhir@gmail.com",
    createdBy: "user_2",
    role: "user",
    isApproved: false,
    featureConfig: {
      viewUser: true,
      createUser: false,
      editUser: false,
      deleteUser: false,
      createWorkFlow: false,
      editWorkFlow: false,
      deleteWorkFlow: false,
      viewWorkFlow: true,
      createDataItem: true,
      editDataItem: false,
      deleteDataItem: false,
      viewDataItem: true,
    },
    permittedRoutes: [
      {
        id: "dashboard",
        label: "Dashboard",
        route: "/dashboard",
        icon: <DashboardOutlined />,
      },
      ...commonRoutes,
    ],
  },
  {
    id: "user_5",
    userName: "user123@gmail.com",
    password: "user@123",
    name: "Sudhir As User",
    createdBy: "user_2",
    email: "sudhir@gmail.com",
    role: "user",
    isApproved: false,
    featureConfig: {
      viewUser: false,
      createUser: false,
      editUser: false,
      deleteUser: false,
      createWorkFlow: false,
      editWorkFlow: false,
      deleteWorkFlow: false,
      viewWorkFlow: true,
      createDataItem: true,
      editDataItem: false,
      deleteDataItem: false,
      viewDataItem: true,
    },
    permittedRoutes: [
      {
        id: "dashboard",
        label: "Dashboard",
        route: "/dashboard",
        icon: <DashboardOutlined />,
      },
      ...commonRoutes,
    ],
  },
];
